apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rwnnl7zpg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rwnnl7zpg-nodejs 
  name: rwnnl7zpg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rwnnl7zpg-nodejs 
